### ISSUE TITLE
Introduce new feature to add to channels also

### ISSUE THREAD

**Issue by jasonpython50** [JohnMiltonHacks/telegram-scraper#5]
Please introduce a new feature to be able to add to channels and also limit ban.

**Comment by tazboys** [comment]
if you comment out "if chat.megagroup==True:" you can get all the chats to show on the screen. including channels and personal chats as well. I have confirmed it works for adding users to channels.

**Comment by jasonpython50** [comment]
Thanks a lot, it worked
